allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  88f2d9a9-688b-4b40-a2dc-38e2776f3907:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-05-20T16:17:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4310b378-ef4d-41d9-8bc3-09511804fb09
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 288a3395-444f-4b9c-b3ae-bdf68c69ee33
        userCondition: null
    thumbFieldKey: null
handle: aboutus
hasTitleField: true
icon: null
name: 'About Us'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
