columnSuffix: null
handle: logoImage
instructions: null
name: 'Logo Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:8e4f54b1-7c53-4dfb-8e38-82025bbd8103' # Images
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:8e4f54b1-7c53-4dfb-8e38-82025bbd8103' # Images
  restrictedLocationSubpath: null
  selectionLabel: 'Add Logo'
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:8e4f54b1-7c53-4dfb-8e38-82025bbd8103' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: thumbs
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
